# Generated by Django 5.2.3 on 2025-07-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['title'], 'verbose_name_plural': 'cities'},
        ),
    ]
